/**
* Lamp Control API
* A simple API for controlling lamps, demonstrating CRUD operations. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.lampcontrol.api.models


import kotlinx.serialization.Serializable
/**
 * 
 * @param status Initial status of the lamp (on/off)
 */
@Serializable
data class LampCreate(
    /* Initial status of the lamp (on/off) */
    val status: kotlin.Boolean
)

