/**
* Lamp Control API
* A simple API for controlling lamps, demonstrating CRUD operations.
*
* The version of the OpenAPI document: 1.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.lampcontrol.api.models

import kotlinx.serialization.*

/**
 *
 * @param id Unique identifier for the lamp
 * @param status Whether the lamp is turned on (true) or off (false)
 * @param createdAt Timestamp when the lamp was created
 * @param updatedAt Timestamp when the lamp was last updated
 */
@Serializable
data class Lamp(
    // Unique identifier for the lamp
    @Contextual val id: java.util.UUID,
    // Whether the lamp is turned on (true) or off (false)
    val status: kotlin.Boolean,
    // Timestamp when the lamp was created
    val createdAt: kotlin.String,
    // Timestamp when the lamp was last updated
    val updatedAt: kotlin.String,
)
