/**
* Lamp Control API
* A simple API for controlling lamps, demonstrating CRUD operations. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.lampcontrol.api.models

import com.lampcontrol.api.models.Lamp

import kotlinx.serialization.Serializable
/**
 * 
 * @param `data` 
 * @param hasMore 
 * @param nextCursor 
 */
@Serializable
data class ListLamps200Response(
    val `data`: kotlin.collections.List<Lamp>,
    val hasMore: kotlin.Boolean,
    val nextCursor: kotlin.String? = null
)

