/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Lamp;
import org.openapitools.model.LampCreate;
import org.openapitools.model.LampUpdate;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "lamps", description = "the lamps API")
public interface LampsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /lamps : Create a new lamp
     *
     * @param lampCreate  (required)
     * @return Lamp created successfully (status code 201)
     */
    @Operation(
        operationId = "createLamp",
        summary = "Create a new lamp",
        responses = {
            @ApiResponse(responseCode = "201", description = "Lamp created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Lamp.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/lamps",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default CompletableFuture<ResponseEntity<Lamp>> createLamp(
        @Parameter(name = "LampCreate", description = "", required = true) @Valid @RequestBody LampCreate lampCreate
    ) {
        return CompletableFuture.supplyAsync(()-> {
            getRequest().ifPresent(request -> {
                for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                    if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                        String exampleString = "{ \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : true }";
                        ApiUtil.setExampleResponse(request, "application/json", exampleString);
                        break;
                    }
                }
            });
            return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
        }, Runnable::run);

    }


    /**
     * DELETE /lamps/{lampId} : Delete a lamp
     *
     * @param lampId  (required)
     * @return Lamp deleted successfully (status code 204)
     *         or Lamp not found (status code 404)
     */
    @Operation(
        operationId = "deleteLamp",
        summary = "Delete a lamp",
        responses = {
            @ApiResponse(responseCode = "204", description = "Lamp deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Lamp not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/lamps/{lampId}"
    )
    
    default CompletableFuture<ResponseEntity<Void>> deleteLamp(
        @Parameter(name = "lampId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("lampId") String lampId
    ) {
        return CompletableFuture.completedFuture(new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED));

    }


    /**
     * GET /lamps/{lampId} : Get a specific lamp
     *
     * @param lampId  (required)
     * @return Lamp details (status code 200)
     *         or Lamp not found (status code 404)
     */
    @Operation(
        operationId = "getLamp",
        summary = "Get a specific lamp",
        responses = {
            @ApiResponse(responseCode = "200", description = "Lamp details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Lamp.class))
            }),
            @ApiResponse(responseCode = "404", description = "Lamp not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/lamps/{lampId}",
        produces = { "application/json" }
    )
    
    default CompletableFuture<ResponseEntity<Lamp>> getLamp(
        @Parameter(name = "lampId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("lampId") String lampId
    ) {
        return CompletableFuture.supplyAsync(()-> {
            getRequest().ifPresent(request -> {
                for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                    if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                        String exampleString = "{ \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : true }";
                        ApiUtil.setExampleResponse(request, "application/json", exampleString);
                        break;
                    }
                }
            });
            return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
        }, Runnable::run);

    }


    /**
     * GET /lamps : List all lamps
     *
     * @return A list of lamps (status code 200)
     */
    @Operation(
        operationId = "listLamps",
        summary = "List all lamps",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of lamps", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Lamp.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/lamps",
        produces = { "application/json" }
    )
    
    default CompletableFuture<ResponseEntity<List<Lamp>>> listLamps(
        
    ) {
        return CompletableFuture.supplyAsync(()-> {
            getRequest().ifPresent(request -> {
                for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                    if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                        String exampleString = "[ { \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : true }, { \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : true } ]";
                        ApiUtil.setExampleResponse(request, "application/json", exampleString);
                        break;
                    }
                }
            });
            return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
        }, Runnable::run);

    }


    /**
     * PUT /lamps/{lampId} : Update a lamp&#39;s status
     *
     * @param lampId  (required)
     * @param lampUpdate  (required)
     * @return Lamp updated successfully (status code 200)
     *         or Lamp not found (status code 404)
     */
    @Operation(
        operationId = "updateLamp",
        summary = "Update a lamp's status",
        responses = {
            @ApiResponse(responseCode = "200", description = "Lamp updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Lamp.class))
            }),
            @ApiResponse(responseCode = "404", description = "Lamp not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/lamps/{lampId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default CompletableFuture<ResponseEntity<Lamp>> updateLamp(
        @Parameter(name = "lampId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("lampId") String lampId,
        @Parameter(name = "LampUpdate", description = "", required = true) @Valid @RequestBody LampUpdate lampUpdate
    ) {
        return CompletableFuture.supplyAsync(()-> {
            getRequest().ifPresent(request -> {
                for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                    if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                        String exampleString = "{ \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : true }";
                        ApiUtil.setExampleResponse(request, "application/json", exampleString);
                        break;
                    }
                }
            });
            return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
        }, Runnable::run);

    }

}
