name: Tests

on: [push, pull_request]

jobs:
    tests:
        name: Tests PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                php: [7.4, 8.0, 8.1]
                experimental: [false]
                include:
                    - php: 8.1
                      analysis: true

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug

            - name: Install dependencies with Composer
              uses: ramsey/composer-install@v2

            - name: Coding standards
              if: matrix.analysis
              run: vendor/bin/phpcs

            - name: Static analysis
              if: matrix.analysis
              run: vendor/bin/phpstan

            - name: Tests
              run: vendor/bin/phpunit --coverage-clover coverage.xml

            - name: Create Pull Request for coverage summary
              if: matrix.analysis && github.event_name == 'workflow_dispatch'
              uses: peter-evans/create-pull-request@v6
              with:
                  commit-message: "chore: update coverage summary"
                  title: "chore: update coverage summary"
                  body: "Automated PR to update coverage.xml after test run."
                  branch: "ci/php-coverage-update"
