<?php

/**
 * Lamp Control API
 * PHP version 8.1
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A simple API for controlling lamps, demonstrating CRUD operations.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\DefaultApi;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\DefaultApi
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createLamp
     *
     * Create a new lamp.
     *
     * @covers ::createLamp
     */
    public function testCreateLamp()
    {
        self::markTestIncomplete(
            'Test of "createLamp" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteLamp
     *
     * Delete a lamp.
     *
     * @covers ::deleteLamp
     */
    public function testDeleteLamp()
    {
        self::markTestIncomplete(
            'Test of "deleteLamp" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getLamp
     *
     * Get a specific lamp.
     *
     * @covers ::getLamp
     */
    public function testGetLamp()
    {
        self::markTestIncomplete(
            'Test of "getLamp" method has not been implemented yet.'
        );
    }

    /**
     * Test case for listLamps
     *
     * List all lamps.
     *
     * @covers ::listLamps
     */
    public function testListLamps()
    {
        self::markTestIncomplete(
            'Test of "listLamps" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateLamp
     *
     * Update a lamp's status.
     *
     * @covers ::updateLamp
     */
    public function testUpdateLamp()
    {
        self::markTestIncomplete(
            'Test of "updateLamp" method has not been implemented yet.'
        );
    }
}
