// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lamps.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLamps = `-- name: CountLamps :one
SELECT COUNT(*) as count
FROM lamps
WHERE deleted_at IS NULL
`

func (q *Queries) CountLamps(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLamps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLamp = `-- name: CreateLamp :one
INSERT INTO lamps (id, is_on, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, is_on, created_at, updated_at, deleted_at
`

type CreateLampParams struct {
	ID        pgtype.UUID        `json:"id"`
	IsOn      bool               `json:"is_on"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLamp(ctx context.Context, arg CreateLampParams) (Lamp, error) {
	row := q.db.QueryRow(ctx, createLamp,
		arg.ID,
		arg.IsOn,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Lamp
	err := row.Scan(
		&i.ID,
		&i.IsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLamp = `-- name: DeleteLamp :execrows
UPDATE lamps
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type DeleteLampParams struct {
	ID        pgtype.UUID        `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteLamp(ctx context.Context, arg DeleteLampParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLamp, arg.ID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllLampsForTest = `-- name: GetAllLampsForTest :many
SELECT id, is_on, created_at, updated_at, deleted_at
FROM lamps
ORDER BY created_at ASC
`

func (q *Queries) GetAllLampsForTest(ctx context.Context) ([]Lamp, error) {
	rows, err := q.db.Query(ctx, getAllLampsForTest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lamp
	for rows.Next() {
		var i Lamp
		if err := rows.Scan(
			&i.ID,
			&i.IsOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLampByID = `-- name: GetLampByID :one
SELECT id, is_on, created_at, updated_at, deleted_at
FROM lamps
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLampByID(ctx context.Context, id pgtype.UUID) (Lamp, error) {
	row := q.db.QueryRow(ctx, getLampByID, id)
	var i Lamp
	err := row.Scan(
		&i.ID,
		&i.IsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLamps = `-- name: ListLamps :many
SELECT id, is_on, created_at, updated_at, deleted_at
FROM lamps
WHERE deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListLampsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLamps(ctx context.Context, arg ListLampsParams) ([]Lamp, error) {
	rows, err := q.db.Query(ctx, listLamps, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lamp
	for rows.Next() {
		var i Lamp
		if err := rows.Scan(
			&i.ID,
			&i.IsOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLamp = `-- name: UpdateLamp :one
UPDATE lamps
SET is_on = $2, updated_at = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, is_on, created_at, updated_at, deleted_at
`

type UpdateLampParams struct {
	ID        pgtype.UUID        `json:"id"`
	IsOn      bool               `json:"is_on"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateLamp(ctx context.Context, arg UpdateLampParams) (Lamp, error) {
	row := q.db.QueryRow(ctx, updateLamp, arg.ID, arg.IsOn, arg.UpdatedAt)
	var i Lamp
	err := row.Scan(
		&i.ID,
		&i.IsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
