// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores lamp entities and their current status
type Lamp struct {
	// Unique identifier for the lamp
	ID pgtype.UUID `json:"id"`
	// Current status of the lamp (true = ON, false = OFF)
	IsOn bool `json:"is_on"`
	// Timestamp when the lamp was created
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Timestamp when the lamp was last updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Timestamp when the lamp was soft deleted, NULL if active
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
