// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountLamps(ctx context.Context) (int64, error)
	CreateLamp(ctx context.Context, arg CreateLampParams) (Lamp, error)
	DeleteLamp(ctx context.Context, arg DeleteLampParams) (int64, error)
	GetAllLampsForTest(ctx context.Context) ([]Lamp, error)
	GetLampByID(ctx context.Context, id pgtype.UUID) (Lamp, error)
	ListLamps(ctx context.Context, arg ListLampsParams) ([]Lamp, error)
	UpdateLamp(ctx context.Context, arg UpdateLampParams) (Lamp, error)
}

var _ Querier = (*Queries)(nil)
