<?php

/**
 * Lamp Control API
 * PHP version 8.1
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A simple API for controlling lamps, demonstrating CRUD operations.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */

namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * Lamp
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Lamp extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "createdAt", "id", "status", "updatedAt" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string",
      "description" : "Unique identifier for the lamp",
      "format" : "uuid"
    },
    "status" : {
      "type" : "boolean",
      "description" : "Whether the lamp is turned on (true) or off (false)"
    },
    "createdAt" : {
      "type" : "string",
      "description" : "Timestamp when the lamp was created",
      "format" : "date-time"
    },
    "updatedAt" : {
      "type" : "string",
      "description" : "Timestamp when the lamp was last updated",
      "format" : "date-time"
    }
  }
}
SCHEMA;
}
