# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Lamp(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Lamp - a model defined in OpenAPI

        id: The id of this Lamp.
        status: The status of this Lamp.
    """

    id: str = Field(alias="id")
    status: bool = Field(alias="status")

Lamp.update_forward_refs()
