
"""
    Lamp Control API

    A simple API for controlling lamps, demonstrating CRUD operations. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from lamp_control_api.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Lamp Control API",
    description="A simple API for controlling lamps, demonstrating CRUD operations. ",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
