<?php

/**
 * Lamp Control API
 * PHP version 8.1
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A simple API for controlling lamps, demonstrating CRUD operations.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\LampUpdate;

/**
 * LampUpdateTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\LampUpdate
 */
class LampUpdateTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LampUpdate"
     */
    public function testLampUpdate()
    {
        $testLampUpdate = new LampUpdate();
        $namespacedClassname = LampUpdate::getModelsNamespace() . '\\LampUpdate';
        $this->assertSame('\\' . LampUpdate::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        
        // Test that the lamp update model can be created
        $this->assertInstanceOf(LampUpdate::class, $testLampUpdate);
        
        // Test setting and getting data
        $lampUpdateData = [
            'status' => false
        ];
        $testLampUpdate->setData($lampUpdateData);
        
        $retrievedData = $testLampUpdate->getData();
        $this->assertEquals($lampUpdateData['status'], $retrievedData->status);
        
        // Test JSON serialization
        $json = json_encode($testLampUpdate);
        $this->assertJson($json);
        $decoded = json_decode($json, true);
        $this->assertEquals($lampUpdateData['status'], $decoded['status']);
        
        // Test creating from data directly
        $lampUpdateFromData = LampUpdate::createFromData(['status' => true]);
        $this->assertInstanceOf(LampUpdate::class, $lampUpdateFromData);
        $this->assertTrue($lampUpdateFromData->status);
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $testLampUpdate = new LampUpdate();
        
        // Test setting status to true
        $testLampUpdate->status = true;
        $this->assertTrue($testLampUpdate->status);
        
        // Test setting status to false
        $testLampUpdate->status = false;
        $this->assertFalse($testLampUpdate->status);
        
        // Test that required status property appears in schema
        $schema = LampUpdate::getOpenApiSchema();
        $this->assertArrayHasKey('required', $schema);
        $this->assertContains('status', $schema['required']);
        $this->assertArrayHasKey('properties', $schema);
        $this->assertArrayHasKey('status', $schema['properties']);
        $this->assertEquals('boolean', $schema['properties']['status']['type']);
        $this->assertEquals('New status of the lamp (on/off)', $schema['properties']['status']['description']);
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = LampUpdate::getOpenApiSchema();
        /** @phpstan-ignore-next-line method.alreadyNarrowedType */
        $this->assertIsArray($schemaArr);
    }
}
