<?php

/**
 * Lamp Control API
 * PHP version 8.1
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * A simple API for controlling lamps, demonstrating CRUD operations.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\ListLamps200Response;

/**
 * ListLamps200ResponseTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\ListLamps200Response
 */
class ListLamps200ResponseTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListLamps200Response"
     */
    public function testListLamps200Response()
    {
        $testListLamps200Response = new ListLamps200Response();
        $namespacedClassname = ListLamps200Response::getModelsNamespace() . '\\ListLamps200Response';
        $this->assertSame('\\' . ListLamps200Response::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        self::markTestIncomplete(
            'Test of "ListLamps200Response" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        self::markTestIncomplete(
            'Test of "data" property in "ListLamps200Response" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "nextCursor"
     */
    public function testPropertyNextCursor()
    {
        self::markTestIncomplete(
            'Test of "nextCursor" property in "ListLamps200Response" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "hasMore"
     */
    public function testPropertyHasMore()
    {
        self::markTestIncomplete(
            'Test of "hasMore" property in "ListLamps200Response" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = ListLamps200Response::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
