/**
* Lamp Control API
* A simple API for controlling lamps, demonstrating CRUD operations.
*
* The version of the OpenAPI document: 1.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@file:Suppress("WildcardImport", "LongMethod", "TooGenericExceptionCaught", "SwallowedException", "FunctionNaming", "MagicNumber")

package com.lampcontrol.api.apis

import com.lampcontrol.api.Paths
import com.lampcontrol.api.models.Error
import com.lampcontrol.api.models.LampCreate
import com.lampcontrol.api.models.LampUpdate
import com.lampcontrol.api.models.ListLamps200Response
import com.lampcontrol.service.LampService
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.request.*
import io.ktor.server.resources.delete
import io.ktor.server.resources.get
import io.ktor.server.resources.post
import io.ktor.server.resources.put
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun Route.DefaultApi(lampService: LampService) {
    post<Paths.createLamp> {
        try {
            val lampCreate = call.receive<LampCreate>()
            val createdLamp = lampService.createLamp(lampCreate)
            call.respond(HttpStatusCode.Created, createdLamp)
        } catch (e: Exception) {
            call.respond(HttpStatusCode.BadRequest, mapOf("error" to "Invalid request body"))
        }
    }

    delete<Paths.deleteLamp> {
        val lampId = it.lampId
        val deleted = lampService.deleteLamp(lampId)
        if (deleted) {
            call.respond(HttpStatusCode.NoContent)
        } else {
            call.respond(HttpStatusCode.NotFound, mapOf("error" to "Lamp not found"))
        }
    }

    get<Paths.getLamp> {
        val lampId = it.lampId
        val lamp = lampService.getLampById(lampId)
        if (lamp != null) {
            call.respond(HttpStatusCode.OK, lamp)
        } else {
            call.respond(HttpStatusCode.NotFound, mapOf("error" to "Lamp not found"))
        }
    }

    get<Paths.listLamps> {
        try {
            // Validate pageSize parameter if provided
            val pageSize = it.pageSize
            if (pageSize != null) {
                if (pageSize < 1 || pageSize > 100) {
                    call.respond(
                        HttpStatusCode.BadRequest,
                        Error(error = "Invalid numeric parameter"),
                    )
                    return@get
                }
            }

            val lamps = lampService.getAllLamps()
            // Construct response object matching OpenAPI schema: { data: [...], hasMore: boolean, nextCursor: string? }
            val response =
                ListLamps200Response(
                    data = lamps,
                    hasMore = false,
                    nextCursor = null,
                )
            call.respond(HttpStatusCode.OK, response)
        } catch (e: Exception) {
            call.respond(
                HttpStatusCode.BadRequest,
                Error(error = "Invalid numeric parameter"),
            )
        }
    }

    put<Paths.updateLamp> {
        try {
            val lampId = it.lampId
            val lampUpdate = call.receive<LampUpdate>()
            val updatedLamp = lampService.updateLamp(lampId, lampUpdate)
            if (updatedLamp != null) {
                call.respond(HttpStatusCode.OK, updatedLamp)
            } else {
                call.respond(HttpStatusCode.NotFound, mapOf("error" to "Lamp not found"))
            }
        } catch (e: Exception) {
            call.respond(HttpStatusCode.BadRequest, mapOf("error" to "Invalid request body"))
        }
    }
}
