/**
* Lamp Control API
* A simple API for controlling lamps, demonstrating CRUD operations.
*
* The version of the OpenAPI document: 1.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@file:Suppress("WildcardImport", "LongMethod", "FunctionNaming", "MagicNumber", "ktlint:standard:function-naming")

package com.lampcontrol.api.apis

import com.lampcontrol.api.Paths
import com.lampcontrol.api.models.*
import com.lampcontrol.service.LampService
import io.ktor.http.*
import io.ktor.server.request.*
import io.ktor.server.resources.delete
import io.ktor.server.resources.get
import io.ktor.server.resources.post
import io.ktor.server.resources.put
import io.ktor.server.response.*
import io.ktor.server.routing.Route

fun Route.DefaultApi(lampService: LampService) {
    post<Paths.createLamp> {
        val lampCreate = call.receive<LampCreate>()
        val createdLamp = lampService.createLamp(lampCreate)
        call.respond(HttpStatusCode.Created, createdLamp)
    }

    delete<Paths.deleteLamp> {
        lampService.deleteLamp(it.lampId)
        call.respond(HttpStatusCode.NoContent)
    }

    get<Paths.getLamp> {
        val lamp = lampService.getLampById(it.lampId)
        call.respond(HttpStatusCode.OK, lamp)
    }

    get<Paths.listLamps> {
        // Validate pageSize parameter if provided
        val pageSize = it.pageSize
        if (pageSize != null && (pageSize < 1 || pageSize > 100)) {
            call.respond(
                HttpStatusCode.BadRequest,
                Error(error = "Invalid numeric parameter"),
            )
            return@get
        }

        val normalizedPageSize = pageSize ?: 25
        val response = lampService.getLampsPage(cursor = it.cursor, pageSize = normalizedPageSize)
        call.respond(HttpStatusCode.OK, response)
    }

    put<Paths.updateLamp> {
        val lampUpdate = call.receive<LampUpdate>()
        val updatedLamp = lampService.updateLamp(it.lampId, lampUpdate)
        call.respond(HttpStatusCode.OK, updatedLamp)
    }
}
