name: Java Code Quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/java/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/java/**'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Check code formatting
      working-directory: ./src/java
      run: mvn spotless:check
    
    - name: Compile code
      working-directory: ./src/java
      run: mvn compile test-compile
    
    - name: Run SpotBugs
      working-directory: ./src/java
      run: mvn spotbugs:check
    
    - name: Run PMD
      working-directory: ./src/java
      run: mvn pmd:check
    
    - name: Run Checkstyle
      working-directory: ./src/java
      run: mvn checkstyle:check
    
    - name: Run tests
      working-directory: ./src/java
      run: mvn test
    
    - name: Generate SpotBugs report
      working-directory: ./src/java
      run: mvn spotbugs:spotbugs
      if: always()
    
    - name: Generate PMD report
      working-directory: ./src/java
      run: mvn pmd:pmd
      if: always()
    
    - name: Generate Checkstyle report
      working-directory: ./src/java
      run: mvn checkstyle:checkstyle
      if: always()
    
    - name: Upload SpotBugs results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: spotbugs-results
        path: src/java/target/spotbugsXml.xml
    
    - name: Upload PMD results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pmd-results
        path: src/java/target/pmd.xml
    
    - name: Upload Checkstyle results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: checkstyle-results
        path: src/java/target/checkstyle-result.xml
