name: TypeScript CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/typescript/**'
      - '.github/workflows/typescript.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/typescript/**'
      - '.github/workflows/typescript.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: src/typescript

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/typescript/package-lock.json

    - name: Install dependencies
      run: npm ci
      
    - name: Type Check
      run: npm run typecheck
      
    - name: Check for lint issues before fixing
      run: |
        git diff --name-only > /tmp/changed_files.txt
        npm run lint || echo "Linting failed, but continuing to show fixes"

    - name: Run lint with auto-fix
      id: lint
      run: |
        npm run lint -- --fix
        git diff > /tmp/lint_fixes.diff
        if [ -s /tmp/lint_fixes.diff ]; then
          echo "Linting issues were auto-fixed. See the job summary for details."
          echo "Lint fixes found. Please apply these changes locally with 'npm run lint -- --fix'" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          cat /tmp/lint_fixes.diff >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          exit 1
        else
          echo "No linting issues found that could be auto-fixed."
        fi

    - name: Post lint diff as PR comment
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const diff = fs.readFileSync('/tmp/lint_fixes.diff', 'utf8');
          if (diff.trim() !== '') {
            const body = `## Lint Fixes Needed\n\nThe following linting issues can be auto-fixed:\n\n\`\`\`diff\n${diff}\n\`\`\`\n\nPlease run \`npm run lint -- --fix\` locally and commit the changes.`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
          }

    - name: Build
      run: npm run build
      
    - name: Run tests with coverage
      run: npm run test:coverage
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: src/typescript/coverage/
        
    - name: Check test coverage threshold
      run: |
        COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Test coverage is below 80% (Current: $COVERAGE%)"
          exit 1
        fi 