name: Update Code Metrics

on:
  push:
    branches: [ main ]
    paths:
      - 'typescript/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: tools/package-lock.json

    - name: Install dependencies
      run: |
        cd tools
        npm ci

    - name: Run TypeScript metrics analysis
      run: |
        cd tools
        node typescript-metrics.js --output-format markdown > metrics.md

    - name: Update COMPARISON.md
      run: |
        # Read the current metrics
        METRICS=$(cat tools/metrics.md)
        
        # Update the metrics section in COMPARISON.md
        awk -v metrics="$METRICS" '
        BEGIN { p=1 }
        /^## Code Metrics$/ { p=0; print; print metrics; next }
        /^##[^#]/ { p=1 }
        p { print }
        ' docs/COMPARISON.md > docs/COMPARISON.md.tmp
        mv docs/COMPARISON.md.tmp docs/COMPARISON.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/COMPARISON.md
        git commit -m "docs: update code metrics in COMPARISON.md" || exit 0
        git push 