name: Update Code Metrics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: tools/package-lock.json

    - name: Install dependencies
      run: |
        cd tools
        npm ci

    - name: Run TypeScript metrics analysis
      run: |
        cd tools
        node typescript-metrics.js --output-format markdown > metrics.md

    - name: Update COMPARISON.md
      run: |
        # Read the current metrics
        METRICS=$(cat tools/metrics.md)
        
        # Update the metrics section in COMPARISON.md
        awk -v metrics="$METRICS" '
        BEGIN { p=1 }
        /^## Code Metrics$/ { p=0; print; print metrics; next }
        /^##[^#]/ { p=1 }
        p { print }
        ' docs/COMPARISON.md > docs/COMPARISON.md.tmp
        mv docs/COMPARISON.md.tmp docs/COMPARISON.md

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "docs: update code metrics in COMPARISON.md"
        title: "docs: update code metrics in COMPARISON.md"
        body: |
          This PR updates the code metrics in COMPARISON.md with the latest measurements:
          - Lines of Code (App and Tests)
          - Halstead Metrics (App and Tests)
          - Test to Code Ratio
          - Code Coverage Percentage
          
          This is an automated PR generated from the latest main branch changes.
        branch: update-metrics
        delete-branch: true 